### ISSUE TITLE
Incorrect meta.description in German localization

### ISSUE THREAD

**Issue by indirpendent** [VeliovGroup/Uniq.site#1]
Eindeutige Namen generator für Projekte, Kampagnen, Marken, Unternehmen und domain-Namen. Suche für eine einzigartige, einfach formuliert und unvergesslichen Namen. Unsere kreativen Prozess suchen inspirieren die richtige Wahl. Wir kombinierten die besten Elemente von web-design und linguistischen algorithmen für eine Art Prozess der Suche nach einem Namen für Ihr Produkt. Wir erstellten sehr benutzerfreundliche Schnittstelle, einfach und klar zu nutzen. Ernst. (Kein Scherz) Nur Zugriff auf unsere web-site von Konferenz-Raum oder von Ihrer couch und finden, dass Besondere \"Wort\". Darüber hinaus werden wir Ihnen helfen, finden Sie eine große domain-Namen/Titel (web-Adresse). Du wirst es nicht glauben, aber auch für einen drei-Buchstaben langen Namen werden Sie in der Lage, ein drei-Buchstaben-domain. Generieren Sie einen Namen für Ihr Boot -, yacht -, pet -, Benutzer-name/nickname, e-mail-Adresse, web-site, Buch, Gedicht, Lied, musical album/track -, Film -, KFZ/Automobil, etc. Einfach nutzen Sie Ihre Vorstellungskraft und unsere Ressourcen für eine erfolgreiche bemühen!

**Comment by dr-dimitru** [comment]
Accepted in 75a90d13bd2c84b4ba97d4752ec65f37a3cfd855
Thank you @Indira-Tairova
